#!/usr/bin/env bash
# Running transfer to server...

if [ $# -ne 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 2
fi
    scp -i 'StrictHostKeyChecking=no' -o "$4" "$1" "$3@$2:~/"