#!/usr/bin/env bash
# Beep-Boop: 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
location="/etc/nginx/sites-enabled/default"
line="location /redirect_me {rewrite ^/(.*)$ https://www.youtube.com/channel/UCAZI43uXzwRgAEzNriNX8Aw/videos permanent;}"
error="error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "36i $line" "$location"
sudo sed -i "25i $error" "$location"
sudo service nginx restart