#!/usr/bin/env bash
# This script uses an until loop to get the same output as the
# prior two scripts.

a=0
# When the variable IS NOT less than 10
until [ ! $a -lt 10 ]
do
   echo Holberton School
   a+=1
done
