#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.

i=0
while [ $i -lt 13 ]
do
    echo "Hour: $i"
    x=1
    while [ $x -lt 60 ]
    do
	echo $x
	let x+=1
    done
    (( i+=1 ))
done
